### ISSUE TITLE
Master thesis of logifix

### ISSUE THREAD

**Issue by algomaster99** [lyxell/logifix#168]
Hi Anton,

I referred to your project because I wanted to learn how to convert JVM bytecode to Datalog facts. I know you do it for Java source code to Datalog facts which could be a useful reference for me. Just reading the code is a bit hard for me to understand as I am not fluent in CPP. Maybe I could read your master thesis that would give me an abstracted version. Could you please share the link? I could not find it on [Diva portal](https://kth.diva-portal.org/smash/resultList.jsf?dswid=7181&language=en&searchType=SIMPLE&query=Anton+Lyxell&af=%5B%5D&aq=%5B%5B%5D%5D&aq2=%5B%5B%5D%5D&aqe=%5B%5D&noOfRows=50&sortOrder=author_sort_asc&sortOrder2=title_sort_asc&onlyFullText=false&sf=all).

**Comment by algomaster99** [comment]
My another question was how have you made datalog facts exhaustive? For example, how do you ensure that every AST element of Java source code is represented as a fact?

**Comment by algomaster99** [comment]
And where do you parse back from datalog facts to the fixed source code?

**Comment by lyxell** [comment]
@algomaster99 Hey Aman, nice to see you! I'll get back to you on Monday!

**Comment by algomaster99** [comment]
Thanks for follow up! I have done a through study of your codebase and I am looking forward to your responses. My email is on my GitHub profile if you want to reach out there.

**Comment by lyxell** [comment]
@algomaster99 You've got mail!
